tasks:
  - name: Start web server
    init: echo ".gitpod.yml\ Starting web server..."
    command: python -m http.server 8000

github:
  prebuilds:
    addBadge: true

ports:
  - port: 8000
    onOpen: open-preview